--mySQL table setup. Not in use yet
CREATE TABLE room (
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    roomCode VARCHAR(4) NOT NULL PRIMARY KEY,
    roomName VARCHAR(32) NOT NULL
);

CREATE TABLE client (
    createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    roomCode VARCHAR(32) NOT NULL,
    userName VARCHAR(32) NOT NULL
);

CREATE TABLE host {
    createdAT DATETIME DEFAULT CURRENT_TIMESTAMP,
    id INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    roomCode VARCHAR(32) NOT NULL,
    userName VARCHAR(32) NOT NULL
}